-- Documentation Metrics Table
BEGIN;

-- Documentation Metrics Table
CREATE TABLE documentation_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    url TEXT NOT NULL CHECK (url ~ '^https?://[^\\s/$.?#].[^\\s]*$'),
    doc_score FLOAT NOT NULL CHECK (doc_score BETWEEN 0 AND 1),
    sections JSONB NOT NULL,
    readability_score FLOAT CHECK (readability_score >= 0),
    code_examples JSONB,
    internal_links JSONB,
    external_links JSONB,
    metadata JSONB
);

-- Indexes for common query patterns
CREATE INDEX idx_doc_score ON documentation_metrics (doc_score);
CREATE INDEX idx_readability ON documentation_metrics (readability_score);
CREATE INDEX idx_url_pattern ON documentation_metrics (url varchar_pattern_ops);

-- RLS Policy
ALTER TABLE documentation_metrics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public documentation metrics are viewable by all"
    ON documentation_metrics FOR SELECT USING (true);

COMMIT;
